# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: okisme
url: http://okisme.github.io
feed: /atom.xml
author_info: <a href="http://okisme.github.io/">liuchunyan</a>

myblog:
  gavatar: images/2.jpg
  gpname: okisme
  linkedin: http://www.linkedin.com/in/
  github: https://github.com/okisme
  email: mailto:lcy_cs@nuaa.edu.cn
  coverimgs: []
  postbgimg: []

categories: [python, books]

theme: jekyll-theme-cayman